steps:
- name: gcr.io/cloud-builders/npm
  args: ['install']
- name: gcr.io/cloud-builders/npm
  args: ['test']
- name: gcr.io/cloud-builders/git
  args: ['push', 'https://github.com/PilotCityInc/PilotCityWeb.git', 'master']
